[package]
name = "oura"
version = "0.1.0"
edition = "2021"

[dependencies]
pallas = "0.1.0"
hex = "0.4.3"
net2 = "0.2.37"
clap = "2.33.3"
log = "0.4.14"
env_logger = "0.9.0"
crossterm = "0.20"
tui = { version = "0.16", default-features = false, features = ['crossterm'] }
merge = "0.1.0"
config = "0.11.0"
serde = "1.0.130"
serde_derive = "1.0.130"
